### ISSUE TITLE
1.7.3 version not available on Bower

### ISSUE THREAD

**Issue by alessioEdudoc** [d-oliveros/ngSmoothScroll#35]
Is there any way to install the 1.7.3 version using Bower?

Thanks

**Comment by sreglitzki** [comment]
+1
Could you please create a tag for version 1.7.3?
There is only one available: 1.7.1.
Thanks!

**Comment by StefanoVollono** [comment]
Hi Oliveros,
any news about this issue?

Thanks

**Comment by alessioEdudoc** [comment]
@ghost thank you for the suggestion!

**Comment by dound** [comment]
Could you please create the tag @d-oliveros ?

**Comment by d-oliveros** [comment]
See https://github.com/d-oliveros/ngSmoothScroll/issues/40
