### ISSUE TITLE
Scrolling to bottom does not work in container

### ISSUE THREAD

**Issue by DjRAST** [d-oliveros/ngSmoothScroll#36]
When using a container ('containerId' is set), the scrolling behaviour is broken when the bottom of the container would be reached by scrolling.

This fixed the problem for me (from line 111):

    var stopAnimation = function () {
        currentLocation = getScrollLocation();
        if(containerPresent) {
            scrollHeight = container.scrollHeight;
            internalHeight = container.clientHeight + currentLocation;
        } else {
            scrollHeight = document.body.scrollheight;
            internalHeight = window.innerHeight + currentLocation;
        }
    ...

**Comment by jasondecamp** [comment]
Fix worked for me, thanks DjRAST. Lets get this merged!

**Comment by d-oliveros** [comment]
Thanks DjRAST, the PR has been merged now.
