### ISSUE TITLE
Version is not still released

### ISSUE THREAD

**Issue by appfeel** [d-oliveros/ngSmoothScroll#40]
When installing from bower install it installs 1.7.1 (not yet published 1.7.3 tag...)

**Comment by EricWVGG** [comment]
same. Needing that container-id support. 

Otherwise seems to work very well, thank you for the effort.

**Comment by nschloe** [comment]
@d-oliveros: You simply need to create a tag for the new version on GitHub, it'll be published through bower automagically afterwards.

**Comment by miqmago** [comment]
From this url you can create a new tag: https://github.com/d-oliveros/ngSmoothScroll/releases

**Comment by d-oliveros** [comment]
Hey guys, sorry I've been really busy with [another project](https://wiselike.com), and I wasn't able to get into this. This release (`v1.7.3`) is not backwards compatible with `v1.7.1` (https://github.com/d-oliveros/ngSmoothScroll/issues/43), so I bumped the version number to `v2.0.0`. You'll have to change the version number in your bower file.

**Comment by dound** [comment]
Thanks @d-oliveros!
