### ISSUE TITLE
 v1.7.4 is not backwards-compatible with v1.7.x

### ISSUE THREAD

**Issue by josketres** [d-oliveros/ngSmoothScroll#43]
The last release `v1.7.4` was released as a `patch release`.
According to [semantic versioning](http://semver.org/) a patch release is for backward-compatible bug fixes.

I'm using bower to manage my dependencies and I have the following dependency:
```
 "ngSmoothScroll": "~1.7.1",
```
which means that I will automatically update to the newest PATCH version.

With the newest release `v1.7.4` the file `angular-smooth-scroll.js` was moved to `dist/angular-smooth-scroll.js` which is breaking the builds of my already released artifacts.

I suggest **making this new release a major release** because it is not backwards-compatible.

**Comment by spencerwi** [comment]
I got burned by this too. Fortunately, I've seen other projects make the same "breaking-change-in-a-patch/minor-release" misstep, otherwise it would have been difficult to figure out.

**Comment by d-oliveros** [comment]
Oh, you are right, this release is not backward-compatible. I deleted the tag `v1.7.4`, and made a new major release for this version.

Thanks for pointing it out @josketres and @spencerwi :+1:
