### ISSUE TITLE
Having a hard time understanding the usage of this directive

### ISSUE THREAD

**Issue by beedaan** [d-oliveros/ngSmoothScroll#51]
I'm trying to understand how to use this directive.  I'm trying to use the basic smoothScroll directive, and not having any succes.

I'm including the minified version of the library in my application.  I also inject the module into my angular app
```javascript
angular.module('myApp', ['smoothScroll'])
```

I've included the attribute in my HTML code
```html
<div smooth-scroll>
```

What am I missing?

[Here is my jsFiddle](https://jsfiddle.net/beedaan/vqypscxj/)

**Comment by lherich** [comment]
Try to use the not minified version.

**Comment by bheus** [comment]
Thank you @lherich, that works for me!
