### ISSUE TITLE
scrollTo broken in min.js but working in .js

### ISSUE THREAD

**Issue by leogout** [d-oliveros/ngSmoothScroll#57]
Hi, I tried to use your directive with the following code :

``` html
<div class="part-1">
     <div scroll-to="part-3">Scroll</div>
</div>
<div class="part-2"></div>
<div class="part-3" id="part-3"></div>
```

When I included the angular-smooth-scroll.min.js file  (I didn't forgot to include it as a dependency as well), nothing happened. I tried in a vanilla app and I got the same result.
By nothing happend I mean:
- No scroll with scroll-to="someId"
- No scroll on document load with smooth-scroll
- No errors
- Tell me if you want me to try something else

After a while, I just tried to include the angular-smooth-scroll.js instead and everything worked fine.

Hope it helped, sorry for my english. Cheers.

**Comment by tobros91** [comment]
Can confirm the same issue.

**Comment by eriol61309146** [comment]
Can confirm the same issue.

**Comment by ggho** [comment]
I had the same issue! 
so glad to see this issue, otherwise I would never tried that.

**Comment by guidokessels** [comment]
Same here. `scroll-to` with an element ID did nothing. The version in `lib` works.

**Comment by ulejon** [comment]
Having the same issue

**Comment by shaysegev** [comment]
Confirming not working in minified

**Comment by devonc0** [comment]
Confirmed:  doesn't work w/ .min.js
Confirmed:  works awesome with .js ( using bound ng-attr-id={{..}} and scroll-to={{..}} )

**Comment by Matoyak** [comment]
Confirming: Doesn't work with minified.
Also confirming: Works fine with unminified.

**Comment by GregorioDiStefano** [comment]
Confirmed.
Just spent hours on this, before seeing this issue... :(

**Comment by heylookalive** [comment]
Same

**Comment by kavil** [comment]
oh my god spent hours on this

**Comment by emersonthis** [comment]
Same issue. Might be relevant that I installed via bower.

**Comment by kameelyan** [comment]
Had the same issue, just resolved it with this fix, also installed via bower on/around Nov 21st.
