### ISSUE TITLE
scrolling not working

### ISSUE THREAD

**Issue by wizjack** [d-oliveros/ngSmoothScroll#64]
Through console logging I can see messages like 'about to scroll to element' and 'scrolled to element' along with the html code but the page doesn't actually scroll to the div with mentioned id. 

I'm using angularjs with ui router. Testing on chrome (newest version)

//code
        var options = {
            duration: 700,
            easing: 'easeInQuad',
            offset: 400,
            callbackBefore: function (element) {
                console.log('about to scroll to element', element);
            },
            callbackAfter: function (element) {
                console.log('scrolled to element', element);
            }
        };

var ele = document.getElementById('about');
smoothScroll(ele,options);

**Comment by tiagodocouto** [comment]
same problem here!
version 1.7.1 its ok!

**Comment by wizjack** [comment]
Do you mean to say it's not working in 2.0.0 and working in 1.7.1. In that case I may have to revert.

**Comment by tiagodocouto** [comment]
yes, I can confirm that

**Comment by celsomtrindade** [comment]
+1 Same here. 

> Note: Only tested with the function `scroll-to="my-id"` when refering to an element ID and a simple `smooth-scroll` to automatic scroll to the element when rendering.

No scroll. Sometimes it scrolls just a pixel. Tested with 1.7.4 and had same results.
Only first version working.

**Comment by alexkb** [comment]
I couldn't get any scrolling occurring (nor did I see any errors) with the minified version, but when I switched to the unminified it started working fine.

**Comment by wizjack** [comment]
Naaa, tried the older version still not working. Does it not work with ui views in place and view not being a single html page, just a thought.

**Comment by celsomtrindade** [comment]
@alexkb same here, version 2.0 works only with unminified version. .min.js doesn't work.

**Comment by celsomtrindade** [comment]
I think it's just a problem with his uglify proccess. I did my own from his original source code using grunt uglify proccess and it's working just fine. In case anyone wants the file, this is it.

Because of the extension limit here, I've renamed the file to a `.txt` extension, you just need to reverse it to `.min.js` and it'll work.

[ngScroll.TXT](https://github.com/d-oliveros/ngSmoothScroll/files/184198/ngScroll.TXT)

**Comment by Matoyak** [comment]
This seems to be the same issue as #57 . Something got borked in the minification process. (I notice there's a pull request for a fixed minified version which references #59 , which is also apparently the same issue as #57 and this one).

**Comment by wizjack** [comment]
I don't have minification problems. I'm using gulp for minifications. I think it's more related to the content area that needs to scroll, in my case it seems there's isn't much area to scroll. I think I can close this.

**Comment by celsomtrindade** [comment]
@wizjack The problem is when using the min file provided in the github, if you do yours (like i did) it should work.

**Comment by wizjack** [comment]
@celsomtrindade mine working fine. :)
On second thoughts I feel documentation can be enhanced by adding a demo/example. Closing this. Thank you all.
